// <auto-generated />
using System;
using DeadDrop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeadDrop.Migrations.DropLink
{
    [DbContext(typeof(DropLinkDbContext))]
    [Migration("20260302022959_AddInviteCodePlaintextCode")]
    partial class AddInviteCodePlaintextCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.DownloadEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DropId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("WasSuccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DropId");

                    b.ToTable("DownloadEvents");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.Drop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeleteAfterDownloads")
                        .HasColumnType("integer");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InviteCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TusFileId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InviteCodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Drops");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.DropLinkInviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MaxBytesPerDrop")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxDropCount")
                        .HasColumnType("integer");

                    b.Property<long?>("MaxTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UsedDropCount")
                        .HasColumnType("integer");

                    b.Property<long>("UsedTotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.DownloadEvent", b =>
                {
                    b.HasOne("DeadDrop.Domain.Entities.DropLink.Drop", "Drop")
                        .WithMany("DownloadEvents")
                        .HasForeignKey("DropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drop");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.Drop", b =>
                {
                    b.HasOne("DeadDrop.Domain.Entities.DropLink.DropLinkInviteCode", "InviteCode")
                        .WithMany("Drops")
                        .HasForeignKey("InviteCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InviteCode");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.Drop", b =>
                {
                    b.Navigation("DownloadEvents");
                });

            modelBuilder.Entity("DeadDrop.Domain.Entities.DropLink.DropLinkInviteCode", b =>
                {
                    b.Navigation("Drops");
                });
#pragma warning restore 612, 618
        }
    }
}
