/**
 * Error codes returned by ErrorHound backend.
 * Keep in sync with ErrorHound NuGet package error codes.
 */
export const ErrorCodes = {
  VALIDATION: "VALIDATION",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_SERVER: "INTERNAL_SERVER",
  DATABASE: "DATABASE",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  TIMEOUT: "TIMEOUT",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PASSWORD_NOT_SET: "PASSWORD_NOT_SET",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_FORBIDDEN: "SESSION_FORBIDDEN",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
